version: '3.4'

services:
  postgres:
    image: postgres:12-alpine
    container_name: 'postgres-hours'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DATABASE_HOST='localhost'
      - DATABASE_TYPE='postgres'
    ports:
      - 5432:5432
  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    restart: always
    environment:
      - 'RABBITMQ_DEFAULT_PASS=password'
      - 'RABBITMQ_DEFAULT_USER=username'
    ports:
      - 15672:15672
      - 5672:5672
  mongo:
    image: mongo
    container_name: mongo_logs
    ports:
      - 27017:27017
    environment:
      MONGO_INITDBROOT_USERNAME: root
      MONGO_INITDBROOT_PASSWORD: password
  mongo-express:
    image: mongo-express
    container_name: mongo-express_logs
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    depends_on:
      - 'mongo'
    restart: unless-stopped
  api:
    container_name: 'api'
    build: ./api
    ports:
      - '3333:3333'
  consumer_a:
    build: ./consumerA
    ports:
      - '3334:3334'
  consumer_b:
    build: ./consumerB
    ports:
      - '3335:3335'
  consumer_c:
    build: ./consumerC
    ports:
      - '3336:3336'
  